version: '3'

services:
#**************************************************************
#               APLICAÇÃO FRONTEND
#**************************************************************
  frontuse:
    image: 'httpd:latest'
    container_name: frontendUse
    ports:
      - '80:80'
      - '443:443'
    volumes:
        - /nfs/general/htmluse:/usr/local/apache2/htdocs
    restart: always
    networks:
      - app-network
#**************************************************************
#               APLICAÇÃO BACKEND
#**************************************************************
  backuse:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backendUse
    restart: always
    ports:
      - "8000:80"
    volumes:
      - /nfs/general/backenduse:/var/www/html
    networks:
    - app-network
 
networks:
  app-network:
    driver: bridge
